### ISSUE TITLE
Переход на user/list по дефолту

### ISSUE THREAD

**Issue by palyuga** [palyuga/car-companion#11]
Продыбать, как перекидывать пользователя сразу на user/list
В идеале - вообще замапить user/list на корень сайта, чтобы пользователь заходил на  sharecar.luxoft.com/  и все.

**Comment by ghost** [comment]
Добавил маппинг корня на user/list, почему-то пришлось поменять еще пути для картинок и скриптов. Теперь они  ищутся от webapp
