### ISSUE TITLE
Какая-то херня с адресами на карте: магистральная улица рядом с Ленина

### ISSUE THREAD

**Issue by ghost** [palyuga/car-companion#16]
![bigbug](https://f.cloud.github.com/assets/1345824/30548/afbd49f2-4eb5-11e2-95b6-bd8c1954553a.png)

**Comment by palyuga** [comment]
Это нормально :) Я руками забивал координаты и адреса у тестовых юзеров. Так что там ничего не соответствует действительности.

**Comment by palyuga** [comment]
Добро пожаловать, йцукен!
